import { Anek_Bangla, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Toaster } from "sonner";
import SimpleFooter from "./Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anekBangla = Anek_Bangla({
  subsets: ["bengali"],
  weight: ["100", "800"],
  variable: "--font-anek-bangla",
  display: "swap",
});

export const metadata = {
  title: "অ্যালামনাই ফর্ম ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${anekBangla.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster richColors position="top-center" closeButton />
        <Navbar />
        {children}
        <SimpleFooter />
      </body>
    </html>
  );
}
